import { ProfileAvatar } from '@/components/dashboard/ProfileAvatar'
import { SectionButton } from '@/components/dashboard/SectionButton'
import type { Metadata } from 'next'
import { LogoutButton } from '@/components/dashboard/LogoutButton'

export const metadata: Metadata = {
  title: 'Start Cursos | ADM Panel',
  description: 'Generated by create next app',
}

const dashboardPages = [
  { id: 1, text: 'Analytics', url: '' },
  { id: 2, text: 'Courses', url: 'courses' },
  { id: 3, text: 'Categories', url: 'categories' },
  { id: 4, text: 'Plans', url: 'plans' },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex h-screen">
      <div className="h-full w-1/5 shadow-indigo-500 shadow-md bg-gray-50">
        <div className="flex flex-col justify-center px-3 py-6 gap-8">
          <div className="flex flex-col justify-center items-center gap-2">
            <ProfileAvatar />
            <h2 className="text-xl font-bold text-gray-800 mb-4">
              João Vitor Bertan
            </h2>
          </div>
          <div className="flex flex-col gap-4 px-2">
            {dashboardPages.map((page) => {
              return (
                <SectionButton key={page.id} text={page.text} url={page.url} />
              )
            })}
          </div>
        </div>
        <LogoutButton />
      </div>
      <div className="w-full">{children}</div>
    </div>
  )
}
